version: "3"

services:
  jjikdan:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
    command: ["./jjikdan", "run cmd/main.go"]
