// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: diary_day.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDiaryDay = `-- name: CreateDiaryDay :one
INSERT INTO diary_day (date)
VALUES ($1)
RETURNING id, date, created_at, updated_at
`

func (q *Queries) CreateDiaryDay(ctx context.Context, date pgtype.Date) (DiaryDay, error) {
	row := q.db.QueryRow(ctx, createDiaryDay, date)
	var i DiaryDay
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findDailySummaryWithDate = `-- name: FindDailySummaryWithDate :one
SELECT diary_date, total_food_moisture, total_salt, average_score FROM diary_daily_summary WHERE diary_date = $1
`

func (q *Queries) FindDailySummaryWithDate(ctx context.Context, diaryDate pgtype.Date) (DiaryDailySummary, error) {
	row := q.db.QueryRow(ctx, findDailySummaryWithDate, diaryDate)
	var i DiaryDailySummary
	err := row.Scan(
		&i.DiaryDate,
		&i.TotalFoodMoisture,
		&i.TotalSalt,
		&i.AverageScore,
	)
	return i, err
}

const findDiaryDayWithDate = `-- name: FindDiaryDayWithDate :one
SELECT id, date, created_at, updated_at FROM diary_day WHERE date = $1
`

func (q *Queries) FindDiaryDayWithDate(ctx context.Context, date pgtype.Date) (DiaryDay, error) {
	row := q.db.QueryRow(ctx, findDiaryDayWithDate, date)
	var i DiaryDay
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findDiaryDayWithMenus = `-- name: FindDiaryDayWithMenus :one
SELECT diary_day_id, diary_date, diary_menus FROM diary_day_view WHERE diary_date = $1
`

func (q *Queries) FindDiaryDayWithMenus(ctx context.Context, diaryDate pgtype.Date) (DiaryDayView, error) {
	row := q.db.QueryRow(ctx, findDiaryDayWithMenus, diaryDate)
	var i DiaryDayView
	err := row.Scan(&i.DiaryDayID, &i.DiaryDate, &i.DiaryMenus)
	return i, err
}
