// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: diary_menu.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDiaryMenu = `-- name: CreateDiaryMenu :one
INSERT INTO diary_menu (diary_day_id, img, summary, total_cal, status, menu_time, date)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, diary_day_id, date, img, summary, total_cal, status, menu_time, created_at, updated_at
`

type CreateDiaryMenuParams struct {
	DiaryDayID *int64       `db:"diary_day_id" json:"diary_day_id"`
	Img        *string      `db:"img" json:"img"`
	Summary    *string      `db:"summary" json:"summary"`
	TotalCal   *int32       `db:"total_cal" json:"total_cal"`
	Status     NullStatus   `db:"status" json:"status"`
	MenuTime   NullMenuTime `db:"menu_time" json:"menu_time"`
	Date       pgtype.Date  `db:"date" json:"date"`
}

func (q *Queries) CreateDiaryMenu(ctx context.Context, arg CreateDiaryMenuParams) (DiaryMenu, error) {
	row := q.db.QueryRow(ctx, createDiaryMenu,
		arg.DiaryDayID,
		arg.Img,
		arg.Summary,
		arg.TotalCal,
		arg.Status,
		arg.MenuTime,
		arg.Date,
	)
	var i DiaryMenu
	err := row.Scan(
		&i.ID,
		&i.DiaryDayID,
		&i.Date,
		&i.Img,
		&i.Summary,
		&i.TotalCal,
		&i.Status,
		&i.MenuTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
