// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: diary_menu.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDiaryMenu = `-- name: CreateDiaryMenu :one
INSERT INTO diary_menu (diary_day_id, img, summary, total_cal,  menu_time, date, food_moisture, salt, score)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, diary_day_id, date, img, summary, total_cal, menu_time, created_at, updated_at, food_moisture, salt, score
`

type CreateDiaryMenuParams struct {
	DiaryDayID   *int64       `db:"diary_day_id" json:"diary_day_id"`
	Img          *string      `db:"img" json:"img"`
	Summary      *string      `db:"summary" json:"summary"`
	TotalCal     *int32       `db:"total_cal" json:"total_cal"`
	MenuTime     NullMenuTime `db:"menu_time" json:"menu_time"`
	Date         pgtype.Date  `db:"date" json:"date"`
	FoodMoisture *int32       `db:"food_moisture" json:"food_moisture"`
	Salt         *int32       `db:"salt" json:"salt"`
	Score        *int32       `db:"score" json:"score"`
}

func (q *Queries) CreateDiaryMenu(ctx context.Context, arg CreateDiaryMenuParams) (DiaryMenu, error) {
	row := q.db.QueryRow(ctx, createDiaryMenu,
		arg.DiaryDayID,
		arg.Img,
		arg.Summary,
		arg.TotalCal,
		arg.MenuTime,
		arg.Date,
		arg.FoodMoisture,
		arg.Salt,
		arg.Score,
	)
	var i DiaryMenu
	err := row.Scan(
		&i.ID,
		&i.DiaryDayID,
		&i.Date,
		&i.Img,
		&i.Summary,
		&i.TotalCal,
		&i.MenuTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FoodMoisture,
		&i.Salt,
		&i.Score,
	)
	return i, err
}
