// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: test_query.sql

package repository

import (
	"context"
)

const plusQuery = `-- name: PlusQuery :exec
SELECT 1+1
`

func (q *Queries) PlusQuery(ctx context.Context) error {
	_, err := q.db.Exec(ctx, plusQuery)
	return err
}
