// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user_query.sql

package repository

import (
	"context"
)

const testQuery = `-- name: TestQuery :one
SELECT id, username, password, created_at, updated_at FROM "user"
`

func (q *Queries) TestQuery(ctx context.Context) (User, error) {
	row := q.db.QueryRow(ctx, testQuery)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
